apiVersion: apps/v1
kind: Deployment
metadata:
  name: bet-builder
  namespace: bet-with-goodall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bet-builder
  template:
    metadata:
      labels:
        app: bet-builder
    spec:
      serviceAccountName: bet-builder
      volumes:
        - name: aws-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: sts.amazonaws.com
                  expirationSeconds: 3600
                  path: token
        - name: config
          configMap:
            name: bet-builder-config
      containers:
        - name: builder
          image: ghcr.io/paulbailey/bet-with-goodall-builder:sha-721c276f033784f145863331a668464b110b45e6
          imagePullPolicy: Always
          env:
            - name: AWS_ROLE_ARN
              value: "arn:aws:iam::020889749910:role/bet-builder"
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
            - name: FDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bet-builder
                  key: FDB_API_KEY
            - name: S3_BUCKET
              value: "bet-with-goodall"
            - name: AWS_REGION
              value: "eu-west-2"
          volumeMounts:
            - name: aws-token
              mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
              readOnly: true
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
