apiVersion: apps/v1
kind: Deployment
metadata:
  name: bet-builder
  namespace: bet-with-goodall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bet-builder
  template:
    metadata:
      labels:
        app: bet-builder
    spec:
      serviceAccountName: bet-builder
      containers:
        - name: builder
          image: ghcr.io/paulbailey/bet-with-goodall-builder:latest
          imagePullPolicy: Always
          env:
            - name: FDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bet-builder
                  key: FDB_API_KEY
            - name: S3_BUCKET
              value: "bet-with-goodall"
            - name: AWS_REGION
              value: "eu-west-2"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: bet-builder-config
