apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bet-builder
  namespace: bet-with-goodall
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    name: bet-builder
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: FDB_API_KEY
      remoteRef:
        key: /homelab/bet-with-goodall/builder/fdb_api_key
