apiVersion: v1
kind: ServiceAccount
metadata:
  name: bet-builder
  namespace: bet-with-goodall
  annotations:
    # IAM role created by infra/ Terraform (infra output: bet_builder_role_arn)
    eks.amazonaws.com/role-arn: arn:aws:iam::020889749910:role/bet-builder
