apiVersion: v1
kind: ServiceAccount
metadata:
  name: bet-builder
  namespace: default
  annotations:
    # Replace with the IAM role ARN created by Terraform
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/bet-builder
