export interface CountryInfo {
  code: string
  fi: string  // flag-icons CSS class suffix, e.g. 'fr', 'gb-eng'
}

const COUNTRIES: Record<string, CountryInfo> = {
  'Algeria':               { code: 'ALG', fi: 'dz' },
  'Argentina':             { code: 'ARG', fi: 'ar' },
  'Australia':             { code: 'AUS', fi: 'au' },
  'Austria':               { code: 'AUT', fi: 'at' },
  'Belgium':               { code: 'BEL', fi: 'be' },
  'Bolivia':               { code: 'BOL', fi: 'bo' },
  'Bosnia-Herzegovina':    { code: 'BIH', fi: 'ba' },
  'Brazil':                { code: 'BRA', fi: 'br' },
  'Cameroon':              { code: 'CMR', fi: 'cm' },
  'Canada':                { code: 'CAN', fi: 'ca' },
  'Cape Verde Islands':    { code: 'CPV', fi: 'cv' },
  'Chile':                 { code: 'CHI', fi: 'cl' },
  'Colombia':              { code: 'COL', fi: 'co' },
  'Congo DR':              { code: 'COD', fi: 'cd' },
  'Costa Rica':            { code: 'CRC', fi: 'cr' },
  'Croatia':               { code: 'CRO', fi: 'hr' },
  'Curaçao':               { code: 'CUW', fi: 'cw' },
  'Czechia':               { code: 'CZE', fi: 'cz' },
  'Denmark':               { code: 'DEN', fi: 'dk' },
  'Ecuador':               { code: 'ECU', fi: 'ec' },
  'Egypt':                 { code: 'EGY', fi: 'eg' },
  'England':               { code: 'ENG', fi: 'gb-eng' },
  'France':                { code: 'FRA', fi: 'fr' },
  'Germany':               { code: 'GER', fi: 'de' },
  'Ghana':                 { code: 'GHA', fi: 'gh' },
  'Haiti':                 { code: 'HAI', fi: 'ht' },
  'Iran':                  { code: 'IRN', fi: 'ir' },
  'Iraq':                  { code: 'IRQ', fi: 'iq' },
  'Italy':                 { code: 'ITA', fi: 'it' },
  'Ivory Coast':           { code: 'CIV', fi: 'ci' },
  'Japan':                 { code: 'JPN', fi: 'jp' },
  'Jordan':                { code: 'JOR', fi: 'jo' },
  'Mali':                  { code: 'MLI', fi: 'ml' },
  'Mexico':                { code: 'MEX', fi: 'mx' },
  'Morocco':               { code: 'MAR', fi: 'ma' },
  'Netherlands':           { code: 'NED', fi: 'nl' },
  'New Zealand':           { code: 'NZL', fi: 'nz' },
  'Nigeria':               { code: 'NGA', fi: 'ng' },
  'Norway':                { code: 'NOR', fi: 'no' },
  'Panama':                { code: 'PAN', fi: 'pa' },
  'Paraguay':              { code: 'PAR', fi: 'py' },
  'Poland':                { code: 'POL', fi: 'pl' },
  'Portugal':              { code: 'POR', fi: 'pt' },
  'Qatar':                 { code: 'QAT', fi: 'qa' },
  'Romania':               { code: 'ROU', fi: 'ro' },
  'Saudi Arabia':          { code: 'KSA', fi: 'sa' },
  'Scotland':              { code: 'SCO', fi: 'gb-sct' },
  'Senegal':               { code: 'SEN', fi: 'sn' },
  'Serbia':                { code: 'SRB', fi: 'rs' },
  'South Africa':          { code: 'RSA', fi: 'za' },
  'South Korea':           { code: 'KOR', fi: 'kr' },
  'Spain':                 { code: 'ESP', fi: 'es' },
  'Sweden':                { code: 'SWE', fi: 'se' },
  'Switzerland':           { code: 'SUI', fi: 'ch' },
  'Tunisia':               { code: 'TUN', fi: 'tn' },
  'Turkey':                { code: 'TUR', fi: 'tr' },
  'Ukraine':               { code: 'UKR', fi: 'ua' },
  'United States':         { code: 'USA', fi: 'us' },
  'Uruguay':               { code: 'URU', fi: 'uy' },
  'USA':                   { code: 'USA', fi: 'us' },
  'Uzbekistan':            { code: 'UZB', fi: 'uz' },
  'Venezuela':             { code: 'VEN', fi: 've' },
}

export function getCountry(name: string): CountryInfo {
  return COUNTRIES[name] ?? { code: name.slice(0, 3).toUpperCase(), fi: '' }
}
